services:

  redis:
    image: redis:7-alpine

  app:
    build: ./app
    image: devops-lab:v1
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
